services:
  api:
    build:
      context: .
    env_file:
      - .env.test
    command: pnpm test:e2e
    depends_on:
      - db_test

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: njsrw
    ports:
      - '5433:5432'  # optional if CI-only
    tmpfs:
      - /var/lib/postgresql/data  # fast, ephemeral DB
