services:
  app:
    build:
      context: .
    env_file:
      - .env.test
    command: pnpm test:e2e
    depends_on:
      - db_test

  db_test:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_realworld_test
    ports:
      - '5433:5432'  # optional if CI-only
    tmpfs:
      - /var/lib/postgresql/data  # fast, ephemeral DB
